---   
  - name: making relevant directory
    vars:
     ansible_ssh_private_key_file: "/home/ansible/.ssh/fuse-code-challenge-key-pair.pem"
    become: true
    file:
     path: "{{ item }}"
     state: directory
     mode: 0777
    with_items:
    - /home/ec2-user/mongo/monogdata
    - /home/ec2-user/mongo/monogLog


  - name: extract archive file into ~/mongo
    become: true
    become_user: "{{ remoteuser }}"
    become_method: sudo
    unarchive:
      src: "{{ mongourl }}"
      dest: ~/mongo
      mode: 0777
      remote_src: yes    
     
  - name: insert/update configuration using a local file
    become_user: "{{ remoteuser }}"
    blockinfile:
      block: "{{ lookup('file', '../files/bashrc.txt') }}"
      dest: "~/.bashrc"
      backup: yes
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
      insertafter: "EOF"   


  