---
#- name: create ec2 instances as defined ny quantity 
#  hosts: localhost
#  vars:
#     ansible_ssh_private_key_file: "/home/ansible/.ssh/fuse-code-challenge-key-pair.pem"
#  vars_files:
#    - vars/main.yml
#  roles:
#     - ec2

  
- name: flume in amazon ami 
  hosts: aws
  roles:
     - flume     

#- name: mongodb in amazon ami 
#  hosts: aws
#  roles:
#     - mongodb       
   