---

- hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: create ec2 instances as defined in ec2_quantity
      local_action:
        module: ec2
        image: "{{ aws_image }}"
        instance_type: "{{ ec2_instance_type }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        keypair: "{{ aws_keypair }}"
        count: "{{ ec2_quantity }}"
        instance_tags: "{{ ec2_instance_tag }}"
        region: "{{ aws_region }}"
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ aws_vpc_subnet }}"
        wait: true
      register: ec2_info
    
    - debug: var=ec2_info
    - debug: var=item
      with_items: ec2_info.instance_ids   

    - add_host: hostname={{ item.public_ip }} groupname={{ app_name }}_{{ server_env }}
      with_items: ec2_info.instances

    - name: checking for ssh connections in port 22 
      wait_for:
        state: started
        host: "{{ item.public_ip }}"
        port: 22
      with_items: ec2_info.instances
